// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm3c9i-DVXbq8AvgMs6k34tOd9WuT0yeU',
    appId: '1:260437895675:web:7478c4682a56d3cdccc35e',
    messagingSenderId: '260437895675',
    projectId: 'signal-34b02',
    authDomain: 'signal-34b02.firebaseapp.com',
    storageBucket: 'signal-34b02.firebasestorage.app',
    measurementId: 'G-PTBG7M3XS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC740g6DbiMLuf9IxlLYoznoCVnCl7unPw',
    appId: '1:260437895675:android:2f6bc1c07c4140fdccc35e',
    messagingSenderId: '260437895675',
    projectId: 'signal-34b02',
    storageBucket: 'signal-34b02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQseYng4MjB2xVdVfMPhKDVueDZlMXbVw',
    appId: '1:260437895675:ios:25aa27e21bf73253ccc35e',
    messagingSenderId: '260437895675',
    projectId: 'signal-34b02',
    storageBucket: 'signal-34b02.firebasestorage.app',
    iosBundleId: 'com.example.signal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm3c9i-DVXbq8AvgMs6k34tOd9WuT0yeU',
    appId: '1:260437895675:web:0eab992180edb902ccc35e',
    messagingSenderId: '260437895675',
    projectId: 'signal-34b02',
    authDomain: 'signal-34b02.firebaseapp.com',
    storageBucket: 'signal-34b02.firebasestorage.app',
    measurementId: 'G-C3540SJY8E',
  );
}
